apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-jyssajsh
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-jyssajsh:8b86553586aab37ec8d70fa19214f9812e5aa593@sha256:4db5ad0653e8d5efc36f11cc4dafea2ac0617a123b0d462762722ca5ebc4c30d
        name: container-image  
